# Generated by Django 6.0 on 2026-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_product_rating_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('cardHolderName', models.CharField(max_length=100)),
                ('cardNumberame', models.CharField(max_length=50)),
                ('cardExpity', models.CharField(max_length=10)),
                ('cardCvv', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
