# Generated by Django 6.0 on 2026-01-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_order_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cardExpity',
            new_name='cardExpiry',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cardNumberame',
            new_name='cardNumber',
        ),
    ]
