# Generated by Django 6.0 on 2026-01-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_cardexpity_order_cardexpiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='TotalPrice',
        ),
    ]
