# Generated by Django 6.0 on 2026-01-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_amount_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='TotalPrice',
            new_name='amount',
        ),
    ]
