# Generated by Django 6.0 on 2026-01-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
