# Generated by Django 6.0 on 2026-01-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
