# Generated by Django 6.0 on 2026-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cardCvv',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cardExpiry',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cardHolderName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cardNumber',
        ),
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
