# Generated by Django 6.0 on 2026-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_remove_orders_cardcvv_remove_orders_cardexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
